<<<<<<< HEAD
/**
 * Marlin 3D Printer Firmware
 * Copyright (c) 2022 MarlinFirmware [https://github.com/MarlinFirmware/Marlin]
 *
 * Based on Sprinter and grbl.
 * Copyright (c) 2011 Camiel Gubbels / Erik van der Zalm
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 */
=======
//===========================================================================
//========================== DO NOT EDIT THIS FILE ==========================
//===========================================================================
>>>>>>> 95811b8c4da547f4ba8f855ac8b2044dee5682a9

/**
 * Prusa_AIO_Warnings.cpp
 * Test Prusa AIO configuration values and give warnings at compile-time.
 */
#include "MarlinConfig.h"
<<<<<<< HEAD
#define PRUSA_AIO_VERSION 20221021
=======
#define PRUSA_AIO_VERSION 20230224
>>>>>>> 95811b8c4da547f4ba8f855ac8b2044dee5682a9

//
// Warnings! Located here so they will appear just once in the build output.
//

/**
 * Prusa AIO Warnings / Reminders
 */
#ifndef NO_PRUSA_AIO_WARNINGS
<<<<<<< HEAD
  #if EITHER(PRUSA_AIO_THERMISTOR_SLICE_450C, PRUSA_AIO_THERMISTOR_TL_T_D500)
    #warning "Safety Warning: Printing above 295°C will require an upgrade from the stock V6 aluminum block or it could melt!"
  #endif

  // Remind users to check U Disk / Flash Drive jumpers since they typically ship in the WiFi position.
  #if BOTH(PRUSA_AIO_MOTHERBOARD_BTT_SKR_V2_0_REV_B, PRUSA_AIO_FLASH_DRIVE_SUPPORT)
    #warning "Ensure U Disk / Flash Drive jumpers are set correctly. (See Page 12 of SKR V2's User Manual https://bit.ly/3am3PNL)"
  #endif

  // TMC2209s/TMC2226s are configured via UART
  #if ENABLED(PRUSA_AIO_DRIVERS_TMC2209) && DISABLED(PRUSA_AIO_BOARD_NO_UART_SPI_JUMPERS)
    #warning "Ensure driver jumpers on your motherboard are set to UART mode".
  #endif

  // TMC5160s/TMC2130s are configured via SPI
  #if EITHER(PRUSA_AIO_DRIVERS_TMC5160, PRUSA_AIO_DRIVERS_TMC2130) && DISABLED(PRUSA_AIO_BOARD_NO_UART_SPI_JUMPERS)
    #warning "Ensure driver jumpers on your motherboard are set to SPI mode."
  #endif

  // TMC2130s run HOT!
  #if ENABLED(PRUSA_AIO_DRIVERS_TMC2130)
    #warning "TMC2130s run hot! Active cooling is essential or drivers will overheat!"
  #endif

  // Remind users of common LCD controller setup issues
  #warning "If your LCD does not light up, you may need to rotate your EXP cable(s) 180° on one end."

  // Remind users to remove onboard SD card from MKS SGEN_L V2 after flashing or they will get a "MEDIA INIT FAIL" error message due to a shared SD_DETECT signal.
  #if ENABLED(PRUSA_AIO_MOTHERBOARD_MKS_SGEN_L_V2)
    #warning "To prevent a 'MEDIA INIT FAIL' error message, remove onboard SD card after updating firmware."
  #endif

  // SKR Mini E3 only has a single EXP connector, so users must connect to EXP3 on BTT Dual Mode TFT
  #if EITHER(PRUSA_AIO_MOTHERBOARD_BTT_SKR_MINI_E3_V3, PRUSA_AIO_MOTHERBOARD_BTT_SKR_MINI_E3_V3_0_1) && ENABLED(PRUSA_AIO_DISPLAY_STOCK_REPRAP_DISCOUNT_SMART_CONTROLLER)
    #warning "Connect EXP cable from EXP1 on motherboard to EXP3 on BigTreeTech Dual Mode TFT."
  #endif

  // No FAN1_PIN available
  #if ENABLED(PRUSA_AIO_NO_FAN1_PIN)
    #warning "Connect hotend cooling fan directly to 24V power source."
  #endif

  // SKR V3 series with 5V fan need DC Mode board
  #if EITHER(PRUSA_AIO_MOTHERBOARD_BTT_SKR_V3_0, PRUSA_AIO_MOTHERBOARD_BTT_SKR_V3_0_EZ) && EITHER(PRUSA_AIO_PART_COOLING_FAN_5V_STOCK_PRUSA_5015, PRUSA_AIO_PART_COOLING_FAN_5V_LDO_DF5015H05S)
    #warning "SKR 3-DC Mode addon is required to run 5V fans on SKR V3/EZ motherboards."
  #endif

#endif
=======

//===========================================================================
//============================== Jumpers/Pins ===============================
//===========================================================================

#if DISABLED(PRUSA_AIO_NO_DRIVER_UART_SPI_JUMPERS)
  #if ENABLED(PRUSA_AIO_DRIVERS_TMC2209) // TMC2209s/TMC2226s are configured via UART
    #warning "Ensure driver jumpers are set to UART mode".
  #elif EITHER(PRUSA_AIO_DRIVERS_TMC5160, PRUSA_AIO_DRIVERS_TMC2130) // TMC5160s/TMC2130s are configured via SPI
    #warning "Ensure driver jumpers are set to SPI mode."
  #endif
#endif

#if ENABLED(PRUSA_AIO_HAS_FIVE_DRIVERS)
  #warning "Five stepper drivers are required for enabled motherboard. E1 stepper driver will be used for Z2."
  // Warn users of potential endstop/DIAG pin conflicts to prevent homing issues when using sensorless homing
  #if ENABLED(USES_DIAG_JUMPERS)
    #warning "DIAG jumpers must be installed for X & Y and removed for Z, Z2 (E1), & E0 or homing and filament runout will not work correctly."
  #elif ENABLED(USES_DIAG_PINS)
    #warning "DIAG pins must be cut or desoldered from Z, Z2 (E1), and E0 drivers or homing and filament runout will not work correctly."
  #endif
#else // Four drivers
  // Warn users of potential endstop/DIAG pin conflicts to prevent homing issues when using sensorless homing
  #if ENABLED(USES_DIAG_JUMPERS)
    #warning "DIAG jumpers must be installed for X & Y and removed for Z & E or homing and filament runout will not work correctly."
  #elif ENABLED(USES_DIAG_PINS)
    #warning "DIAG pins must be cut or desoldered from Z and E drivers or homing and filament runout will not work correctly."
  #endif
#endif

// Remind users to check U Disk / Flash Drive jumpers since they typically ship in the WiFi position.
#if BOTH(PRUSA_AIO_MOTHERBOARD_BTT_SKR_V2_0_REV_B, PRUSA_AIO_FLASH_DRIVE_SUPPORT)
  #warning "Ensure U Disk / Flash Drive jumpers are set correctly. (See Page 12 of SKR V2's User Manual https://bit.ly/3am3PNL)"
#endif

//===========================================================================
//========================= LCD / TFT / Controller ==========================
//===========================================================================

// Remind users of common LCD controller setup issues
#if ENABLED(PRUSA_AIO_SINGLE_EXP_CONNECTION)
  #warning "Connect EXP cable from EXP1 on motherboard to EXP3 on BigTreeTech Dual Mode TFT. If LCD does not light up, try rotating EXP cable 180° on one end."
#else
  #warning "If LCD does not light up, try rotating EXP cables 180° on one end."
#endif

// Remind users to remove onboard SD card after flashing or they will get a "MEDIA INIT FAIL" error message due to a shared SD_DETECT signal
#if ENABLED(PRUSA_AIO_MEDIA_INIT_WARNING)
  #warning "To prevent a 'MEDIA INIT FAIL' error message, remove onboard SD card after updating firmware."
#endif

//===========================================================================
//================================== Fans ===================================
//===========================================================================

// No FAN1_PIN available
#if ENABLED(PRUSA_AIO_NO_FAN1_PIN)
  #warning "No FAN1_PIN available for automatic hotend cooling. Connect hotend cooling fan directly to 24V power source."
#endif

// BTT002 fan pin reassignment
#if ENABLED(PRUSA_AIO_MOTHERBOARD_BTT_BTT002)
  #warning "Define MK3_FAN_PINS to swap hotend and part cooling fan pins."
#endif

// SKR V3 series with 5V fan need DC Mode board
#if EITHER(PRUSA_AIO_MOTHERBOARD_BTT_SKR_V3_0, PRUSA_AIO_MOTHERBOARD_BTT_SKR_V3_0_EZ) && EITHER(PRUSA_AIO_PART_COOLING_FAN_5V_STOCK_PRUSA_5015, PRUSA_AIO_PART_COOLING_FAN_5V_LDO_DF5015H05S)
  #warning "SKR 3-DC Mode addon is required to run 5V fans on SKR V3/EZ motherboards."
#endif

//===========================================================================
//============================== Temperatures ===============================
//===========================================================================

#if EITHER(PRUSA_AIO_THERMISTOR_SLICE_450C, PRUSA_AIO_THERMISTOR_TL_T_D500)
  #warning "Safety Warning: Printing above 295°C will require an upgrade from the stock V6 aluminum block or it could melt!"
#endif

// TMC2130s run HOT!
#if ENABLED(PRUSA_AIO_DRIVERS_TMC2130)
  #warning "TMC2130s run hot! Active cooling is essential or drivers will overheat!"
#endif

#endif // NO_PRUSA_AIO_WARNINGS
>>>>>>> 95811b8c4da547f4ba8f855ac8b2044dee5682a9
