blank_issues_enabled: false
contact_links:
  - name: 🔗 Prusa AIO Discussion Forum
    url: https://github.com/thisiskeithb/PrusaAIO/discussions
    about: A searchable Prusa AIO Firmware forum.
  - name: 📖 Marlin Documentation
    url: https://marlinfw.org/
    about: Lots of documentation on installing and using Marlin.
  - name: 💸 Want to donate?
    url: https://github.com/sponsors/thisiskeithb
    about: Please take a look at the various options to support thisiskeithb & Prusa AIO's development financially!
